title: AWS Advanced Drivers
description: Documentation for AWS Advanced JDBC, Python, Node.js, Go, .NET, and ODBC Drivers
baseurl: "/aws-advanced-drivers"
url: "https://aws.github.io"

markdown: kramdown

navigation:
  - title: Home
    url: /
  - title: JDBC Wrapper
    url: /jdbc
  - title: Python Wrapper
    url: /python
  - title: Node.js Wrapper
    url: /nodejs
  - title: Go Wrapper
    url: /go
